# Use postgres/example user/password credentials

services:

  pgDb:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
     - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: exampleDb
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    
  mongoDb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  # mongo-express is a web interface for MongoDB
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  # adminer is a web interface for PostgreSQL and other sql databases
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
