
services:
  pgDb:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: exampleDb
      POSTGRES_USER: exampleU
      POSTGRES_PASSWORD: exampleP

#   auth:
#     build:
#       context: ./auth
#     container_name: c_auth
#     ports: 
#       - 8001:8001
#     networks:
#       - ntw_hg01

#   common:
#     build:
#       context: ./common
#     container_name: c_common
#     networks:
#       - ntw_hg01

# networks:
#   ntw_hg01:
#     driver: bridge
  
  # adminer is a web interface for PostgreSQL and other sql databases
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8081:8080
